name: Smoke Test
on:
  pull_request: {}
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          persist-credentials: false
          fetch-depth: '0'
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          make test
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
        with:
          # renovate: datasource=docker depName=golangci/golangci-lint
          version: v1.64.8
          skip-cache: true
          args: "--out-${NO_FUTURE}format colored-line-number --verbose --modules-download-mode=vendor"
